---
- hosts: all
  become: yes

  pre_tasks:
    - name: update apt cache if needed
      apt: "update_cache=yes cache_valid_time=36000"

    # - debug: var=repo_stat
    - name: Check if git repo exists
      stat: path=/opt/yolo
      register: repo_stat

    - name: Fetch the Yolo git repo
      git:
        repo: https://github.com/nkmakau/yolo.git
        dest: path=/opt/yolo
      when: not repo_stat.stat.exists

  tasks:
    # Install nodejs and npm on the client host
    - block:
          - name: Install nodejs and npm on the client
            apt:
                state: present
                name: 
                      - nodejs
                      - npm
                      - build-essential
          
          - name: Check git repo folder exists
            stat: path=/opt/yolo/client
            register: git_stat
          
          - name: Copy the client directory to vagrant
            command: mv /opt/yolo/client /home/vagrant
            when: git_stat.stat.exists

          - name: Install required modules in package.json
            command: >
                  chdir=/home/vagrant/client
                  npm run build

          - name: Run NPM for production
            command: >
                  chdir=/home/vagrant/client
                  npm install -g serve

          - name: Create nohup.out file
            file:
                  path: "/home/vagrant/nohup.out"
                  state: touch

          - name: Start the client app
            shell: 
                  "nohup serve -s build -l 3000 </dev/null >/dev/null 2>&1 & "
            args:
                  chdir: "/home/vagrant/client"
      when: inventory_hostname == "client"



          
          


